### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by AblazingHeart** [Richard-Weiss/Bing-Creator-Image-Downloader#1]
I extracted the zip and put the links in the .txt then I downloaded the gecko driver exe from github and edited the .py to "C:\\Todo\\user\\Descargas\\AI\\gecko" but running the .py just opens a cmd window for an instant an then closes

**Comment by Richard-Weiss** [comment]
Hey @AblazingHeart,

**Comment by Richard-Weiss** [comment]
Hey @AblazingHeart,
there are actually more steps involved and I didn't think of writing them out.
I'm actually working on making the code asynchronous now, so it'll be a lot more efficient.
After that I will write a more detailed documentation on how to use it.
I should be done with it around Sunday this week.
Meanwhile I would recommend that you use an IDE like PyCharm to execute the script.
I'll also add this information to the README when I'm done with the rewrite. 🙂

**Comment by AblazingHeart** [comment]
thanks for your efforts!

**Comment by Richard-Weiss** [comment]
@AblazingHeart I've finished the rewrite and updated the README. Let me know if it works for you. If you have any issues you can't resolve with Google or AI assistance please let me know. 🙂
