### ISSUE TITLE
Can't extract imageId and imageSetId

### ISSUE THREAD

**Issue by Richard-Weiss** [Richard-Weiss/Bing-Creator-Image-Downloader#13]
Sorry if this is a silly problem. I just tried this today with everything at the most recent version. After installing everything, I get this response when I try to run python .\main.py . Is this an installation error or am I just using it wrong? If you could, any advice would be greatly appreciated as the tool seems absolutely wonderful. I put this here because I assumed I was the issue and not something with the code.

2023-11-18 01:53:19,842 INFO Fetching metadata of collections...
Traceback (most recent call last):
  File "C:\PATH\main.py", line 381, in <module>
    asyncio.run(main())
  File "C:\PATH\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\PATH\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\PATH\main.py", line 369, in main
    await set_creation_dates(image_data)
  File "C:\PATH\main.py", line 254, in set_creation_dates
    await asyncio.gather(*tasks)
  File "C:\PATH\main.py", line 258, in _set_creation_date
    extracted_ids = await _extract_set_and_image_id(image['image_page_url'])
  File "C:\PATH\main.py", line 290, in _extract_set_and_image_id
    image_set_id = result.group('image_set_id')
AttributeError: 'NoneType' object has no attribute 'group'

_Originally posted by @jinxyz1 in https://github.com/Richard-Weiss/Bing-Creator-Image-Downloader/discussions/2#discussioncomment-7605217_

**Comment by Richard-Weiss** [comment]
@jinxyz1 I've added the branch [13-image-and-set-id](https://github.com/Richard-Weiss/Bing-Creator-Image-Downloader/tree/13-image-and-set-id) for this.  
Please pull the branch and upload the 13_bing_images.log file after execution so I can inspect the supplied urls.

**Comment by jinxyz1** [comment]
[13_bing_images.log](https://github.com/Richard-Weiss/Bing-Creator-Image-Downloader/files/13402280/13_bing_images.log)
Thank you for the quick response, here is the 13_bing_images.log
If anything else is needed, please let me know.

**Comment by Richard-Weiss** [comment]
@jinxyz1 Thanks. It seems like there is a `1-` before the image set id for some reason which causes this issue.  
It seems like this pattern exists for all your images.  
I can add an exception for it, but there might be similar issues in the future since I don't understand the reasoning behind it.  
I'll create a quick commit for it which will address this case.

**Comment by Richard-Weiss** [comment]
@jinxyz1 You can try out the new commit now by pulling the branch again.  
If there is a `Finished downloading x images in x seconds.` entry at the end it worked.  
You can also send me the stack trace from the terminal and the log if there any other problems though.

**Comment by jinxyz1** [comment]
Thank you again for the quick response. The bing folder now downloads for 1 of the 2 accounts I would like to download for. However, there is not a Finished downloading x images in x seconds entry at the end in either case and I cannot find the meta data in the images that do download with the original prompt. I have re-uploaded the log file with both download attempts. I am sorry but I do not know how to attain the stack trace. Again, thank you for the assistance.
[13_bing_images.log](https://github.com/Richard-Weiss/Bing-Creator-Image-Downloader/files/13404504/13_bing_images.log)

**Comment by Richard-Weiss** [comment]
@jinxyz1 It seems to have worked for the second account.  
I meant the last line in the log, you won't see anything for now in the terminal except for errors, as I'm writing everything to the log file.  
For the first account, you will need to change the cookie if you are switching accounts.  
I could probably add an array for using multiple cookies in the .toml, but this is out of scope for this PR.  
For now, I'll actually fix the output that should have been displayed if no collections are returned.  
Thanks for inadvertently bringing it up. 😄

**Comment by jinxyz1** [comment]
I am glad I managed to do something. Also I tested and the exception now displays. I suppose that one account just has a bum cookie somehow. Just to make sure, the original prompt should be in the data of each image right? I can't find it by looking at the properties of the image. Apologies for not understanding "EXIF Metadata in the UserComment field in a JSON format" but how do I see the prompt and link? I promise to close this afterwords, you've been very gracious with your help.

**Comment by Richard-Weiss** [comment]
@jinxyz1 EXIF has many different fields and one of them is the UserComment which is rarely used and can store relatively much data.    
You may have to find a dedicated EXIF metadata reader like https://github.com/FrankBijnen/ExifToolGui/ or something like Adobe Bridge (it's free, but you'll also need to install creative cloud which is also free).  
Also you don't have to worry or anything.  
You are not annoying me, it's actually quite nice to get such detailed and fast feedback. 😊  
Please don't hesitate to ask any questions you might have.  
Also you don't have to close the issue, I'll do it once I get the branch ready to be merged and merged it into main.
