### ISSUE TITLE
File strategy indices not continuous

### ISSUE THREAD

**Issue by Richard-Weiss** [Richard-Weiss/Bing-Creator-Image-Downloader#37]
If there are some images that can't be downloaded, the are some gaps in the indices.
Setting the indices should happen later in the program to prevent this.

**Comment by rc-gr** [comment]
Btw, I noticed that this was closed as I was writing this. You've probably noticed, but I wish to point this out for future reference.

@Richard-Weiss It's fine as-is though. If I wish to reattempt the download and get another incomplete set, I could easily combine and overwrite them on my system. For example, if I have the following two attempts with the following 3 unique example file names under how it currently works: 

```
2023-10-13T0600Z_0001....jpg
(0002 failed)
2023-10-15T0649Z_0003....jpg
```
and
```
(0001 failed)
2023-10-14T0607Z_0002....jpg
2023-10-15T0649Z_0003....jpg
```
I could easily merge them and get the 3 files in the correct order:
```
2023-10-13T0600Z_0001....jpg
2023-10-14T0607Z_0002....jpg
2023-10-15T0649Z_0003....jpg
```
Had this issue been addressed, I would've ended up like so:
```
2023-10-14T0607Z_0001....jpg
2023-10-15T0649Z_0002....jpg
```
and
```
2023-10-13T0600Z_0001....jpg
2023-10-15T0649Z_0002....jpg
```
which would've resulted in the following after the merge:
```
2023-10-13T0600Z_0001....jpg
2023-10-14T0607Z_0001....jpg
2023-10-15T0649Z_0002....jpg
```

**Comment by Richard-Weiss** [comment]
@rc-gr 
Yeah, I just noticed that it wasn't really feasible with how everything is implemented right now.
