### ISSUE TITLE
Enhancement: Use thumbnails as fallback and indicate as such in the filename and/or EXIF

### ISSUE THREAD

**Issue by rc-gr** [Richard-Weiss/Bing-Creator-Image-Downloader#7]
Instead of failing to download images that have been removed, download the thumbnail version from the thumbnail URL as a fallback, which can be obtained via, in an item in a collection, `item['content']['thumbnails'][0]['thumbnailUrl']`. The arguments would need to be sliced off to obtain the maximum resolution.

Then, indicate somewhere in the file that it has been replaced with the thumbnail. For example, in the filename case, something like `T_<prompt>_1.jpg`. In the EXIF case, one way I could think of would be to add the URL as eg. `thumbnail_link` and append it in the comments. But all images would consequently have them as a trade off.

**Comment by Richard-Weiss** [comment]
@rc-gr I could try implementing something like that, but it would be hard to test as that never happened to me.  
The original image link don't get deleted usually.  
If a prompt is blocked or an image of a run is blocked, there won't be an image  to begin with.  
Can you show me such a case so I can replicate if I'll implement this feature?

**Comment by Richard-Weiss** [comment]
@rc-gr I've looked into the current behavior when an image download fails by triggering it artificially and I think I'll add the thumbnail feature and additional filtering of None values for the file_names to be safe.

**Comment by rc-gr** [comment]
> @rc-gr I could try implementing something like that, but it would be hard to test as that never happened to me. The original image link don't get deleted usually. If a prompt is blocked or an image of a run is blocked, there won't be an image to begin with. Can you show me such a case so I can replicate if I'll implement this feature?

From what I can tell, as of now, those who started collecting from DALL-E 3 onwards should not experience this whatsoever...yet. I ran the program through hundreds of DALL-E 3 prompts, including those I have from as early as 3rd Oct where getting censored was unheard of, and did not experience a single failed download for them.

Those that did fail, however, are the ones that I managed to successfully generate from DALL-E 2.5 and were saved into a collection at the time, but whose image was then removed for whatever reason later on. For such items, their thumbnails are still valid and preserved in the collections, but the image at the prompt's page now looks like this:

![ImageCreator](https://github.com/Richard-Weiss/Bing-Creator-Image-Downloader/assets/138417636/5502989a-8cbe-43bc-89bd-9f3f74a9a669)

As you can see in this case, the prompt's page is also valid, and one could even navigate to the other images in the prompt, where they may or may not be blocked like this one.

Anyway, I appreciate the attempt to implement it anyway, especially considering this may happen to images that are saved to collections now, but gets blocked for whatever new policy Bing might implement later on.

**Comment by Richard-Weiss** [comment]
@rc-gr btw I won't be able to work on this until the 18th of November, but feel free to fork the repo and create a PR if you want it earlier.
